### PR TITLE
Team cards

### PR DESCRIPTION
**Pull request by aitikgupta**
Add Teams component

### CODE REVIEW

**Review by anjalisoni3655 — CHANGES_REQUESTED** [review]
Please add the picture of the new UI and some description about the new UI changes

**Review by anjalisoni3655 — CHANGES_REQUESTED** [review]
Can we change the image dimensions, like changing the height, width, and the border radius to this?
 width: "150px",
    height: "200px",
    borderRadius: "50%",
Screenshot from 2021-02-06 21-17-53

**Comment by anjalisoni3655** [comment]
> Can we change the image dimensions, like changing the height, width, and the border radius to this?
> width: "150px",
> height: "200px",
> borderRadius: "50%",
> Screenshot from 2021-02-06 21-17-53

just a suggestion, it looks good to me..

**Comment by aitikgupta** [comment]
> Can we change the image dimensions, like changing the height, width, and the border radius to this?
width: "150px",
height: "200px",
borderRadius: "50%",

Sure this looks good with your profile which is in portrait, I'm suggesting another PR for actually adding the images.
How good they look and the changes we can decide later.

**Review by anjalisoni3655 — APPROVED** [review]
Let's update the team details after this.

**Pull request merged**
