### PR TITLE
Some aethetic changes

### PR DESCRIPTION
**Pull request by aitikgupta**

### CODE REVIEW

**Review by anjalisoni3655 — CHANGES_REQUESTED** [review]
add some photos or details about the changes that you have done, it will be easy for review then.

**Comment by anjalisoni3655** [comment]
> add some photos or details about the changes that you have done, it will be easy for review then.

Screenshot from 2021-02-06 21-22-48
In the above picture, screen resolution is 100% of my browser, the bottom text is partially visible? Can we do something that it adjusts as per the screen size and both the texts as well as the gif, is visible as the introduction?

**Comment by aitikgupta** [comment]
> In the above picture, screen resolution is 100% of my browser, the bottom text is partially visible? Can we do something that it adjusts as per the screen size and both the texts as well as the gif, is visible as the introduction?

There should be :/

**Comment by aitikgupta** [comment]
The changes:
Peek 2021-02-06 21-46

**Review by anjalisoni3655 — APPROVED** [review]
LGTM!!

**Pull request merged**
